[2024-07-30T10:28:22.478+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-30T10:28:22.524+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-28T00:00:00+00:00 [queued]>
[2024-07-30T10:28:22.539+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-28T00:00:00+00:00 [queued]>
[2024-07-30T10:28:22.540+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-30T10:28:22.699+0000] {taskinstance.py:2330} INFO - Executing <Task(DataQualityOperator): Run_data_quality_checks> on 2018-11-28 00:00:00+00:00
[2024-07-30T10:28:22.708+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1406) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-30T10:28:22.710+0000] {standard_task_runner.py:63} INFO - Started process 1408 to run task
[2024-07-30T10:28:22.708+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipelinev5', 'Run_data_quality_checks', 'scheduled__2018-11-28T00:00:00+00:00', '--job-id', '294', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpqabxzphz']
[2024-07-30T10:28:22.712+0000] {standard_task_runner.py:91} INFO - Job 294: Subtask Run_data_quality_checks
[2024-07-30T10:28:22.858+0000] {task_command.py:426} INFO - Running <TaskInstance: pipelinev5.Run_data_quality_checks scheduled__2018-11-28T00:00:00+00:00 [running]> on host c3b60429ae20
[2024-07-30T10:28:23.201+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipelinev5' AIRFLOW_CTX_TASK_ID='Run_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2018-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2018-11-28T00:00:00+00:00'
[2024-07-30T10:28:23.202+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-30T10:28:23.227+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for songplays table
[2024-07-30T10:28:23.246+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:28:23.286+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM songplays, parameters: None
[2024-07-30T10:28:23.296+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:28:23.301+0000] {data_quality_operator.py:30} INFO - Data quality on table songplays check passed with 6490 records
[2024-07-30T10:28:23.303+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for users table
[2024-07-30T10:28:23.326+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:28:23.357+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM users, parameters: None
[2024-07-30T10:28:23.363+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:28:23.366+0000] {data_quality_operator.py:30} INFO - Data quality on table users check passed with 96 records
[2024-07-30T10:28:23.367+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for songs table
[2024-07-30T10:28:23.385+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:28:23.409+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM songs, parameters: None
[2024-07-30T10:28:23.415+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:28:23.418+0000] {data_quality_operator.py:30} INFO - Data quality on table songs check passed with 71 records
[2024-07-30T10:28:23.419+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for artists table
[2024-07-30T10:28:23.439+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:28:23.468+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM artists, parameters: None
[2024-07-30T10:28:23.474+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:28:23.478+0000] {data_quality_operator.py:30} INFO - Data quality on table artists check passed with 69 records
[2024-07-30T10:28:23.479+0000] {data_quality_operator.py:23} INFO - Checking Data Quality for times table
[2024-07-30T10:28:23.495+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-07-30T10:28:23.520+0000] {sql.py:487} INFO - Running statement: SELECT COUNT(*) FROM times, parameters: None
[2024-07-30T10:28:23.526+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-30T10:28:23.530+0000] {data_quality_operator.py:30} INFO - Data quality on table times check passed with 6483 records
[2024-07-30T10:28:23.532+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-30T10:28:23.556+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipelinev5, task_id=Run_data_quality_checks, run_id=scheduled__2018-11-28T00:00:00+00:00, execution_date=20181128T000000, start_date=20240730T102822, end_date=20240730T102823
[2024-07-30T10:28:23.729+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-30T10:28:23.767+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-30T10:28:23.800+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
